server:
  port: 8082
finnhub:
  api:
    key: "d312t59r01qnu2r09ktgd312t59r01qnu2r09ku0"  # 從 Finnhub 註冊取得

# PostgreSQL datasource configuration
spring:
  datasource:
    url: "jdbc:postgresql://postgres-container:5432/SNP500"
    username: "postgres"
    password: "admin1234"
    driver-class-name: "org.postgresql.Driver" # 明確指定驅動類
  jpa:
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect" # 設定 PostgreSQL 方言
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: "redis-container"
      port: 6379
      database: 0
      timeout: 2000

project:
  data:
    provider:
      url: "http://localhost:8081"

# SQL command to alter the table
sql:
  - "ALTER TABLE stocks ADD COLUMN id SERIAL PRIMARY KEY;"
  - "ALTER TABLE stocks ADD PRIMARY KEY (symbol);"
