server:
  port: 8082
finnhub:
  api:
    key: "d312t59r01qnu2r09ktgd312t59r01qnu2r09ku0"  # 從 Finnhub 註冊取得

# PostgreSQL datasource configuration
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver" # 明確指定驅動類
    url: "jdbc:postgresql://postgres-container:5432/SNP500"
    username: "postgres"
    password: "admin1234"
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  data:
    redis:
      host: "redis-container"
      port: 6379
      database: 0
      timeout: 2000

project-data-provider:
  base:
    url: "http://project-data-provider:8081"

# SQL command to alter the table
sql:
  - "ALTER TABLE stocks ADD COLUMN id SERIAL PRIMARY KEY;"
  - "ALTER TABLE stocks ADD PRIMARY KEY (symbol);"
