services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: SNP500
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - bootcamp-network
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis-container
    networks:
      - bootcamp-network
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data:/data"

  data-provider-app:
    image: project-data-provider:0.0.1
    container_name: project-data-provider
    networks:
      - bootcamp-network
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis

  stock-data-app:
    image: project-stock-data:0.0.1
    container_name: project-stock-data
    networks:
      - bootcamp-network
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy  # 等待 PostgreSQL 服務健康後再啟動
      project-data-provider:
        condition: service_started
      redis:
        condition: service_started

  heatmap-ui-app:
    image: project-heatmap-ui:0.0.1
    container_name: project-heatmap-ui
    networks:
      - bootcamp-network
    ports:
      - "8080:8080"
    depends_on:
      - project-stock-data

networks:
  bootcamp-network:
    driver: bridge

volumes:
  redis_data: