server:
  port: 8080
project:
  stock:
    data:
      url: "http://localhost:8082"

# PostgreSQL datasource configuration
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/SNP500
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver