server:
  port: 8080
  
project-stock-data:
  base:
    url: "http://project-stock-data:8082"

# PostgreSQL datasource configuration
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgres-container:5432/SNP500"
    username: "postgres"
    password: "admin1234"
