server:
  port: 8081
finnhub:
  api:
    key: d312t59r01qnu2r09ktgd312t59r01qnu2r09ku0  # 從 Finnhub 註冊取得

# PostgreSQL datasource configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SNP500
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
